/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.VentaDTO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marki
 */
public class PantallaReporteVentas extends javax.swing.JFrame {
    private JTextField txtFechaInicio;
    private JTextField txtFechaFin;
    private JButton btnGenerar;

    private JLabel lblTotalIngresos;
    private JLabel lblKilosVendidos;

    private JTable tablaVentas;
    private DefaultTableModel modelo;
    /**
     * Creates new form PantallaReporteVentas
     */
    public PantallaReporteVentas() {

        setTitle("Reporte de Ventas");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        //Filtros
        JPanel panelFiltros = new JPanel();
        panelFiltros.add(new JLabel("Inicio:"));
        txtFechaInicio = new JTextField(10);
        panelFiltros.add(txtFechaInicio);

        panelFiltros.add(new JLabel("Fin:"));
        txtFechaFin = new JTextField(10);
        panelFiltros.add(txtFechaFin);

        btnGenerar = new JButton("Generar");
        panelFiltros.add(btnGenerar);

        add(panelFiltros, BorderLayout.NORTH);

        // Centro
        JPanel panelCentro = new JPanel(new BorderLayout());

        JPanel panelResumen = new JPanel(new GridLayout(1, 2));
        lblTotalIngresos = new JLabel("Total: $0");
        lblKilosVendidos = new JLabel("Kilos: 0");

        panelResumen.add(lblTotalIngresos);
        panelResumen.add(lblKilosVendidos);

        panelCentro.add(panelResumen, BorderLayout.NORTH);

        // Tabla 
        modelo = new DefaultTableModel(
                new Object[]{"Fecha", "Cantidad", "Total"}, 0
        );

        tablaVentas = new JTable(modelo);
        panelCentro.add(new JScrollPane(tablaVentas), BorderLayout.CENTER);

        add(panelCentro, BorderLayout.CENTER);
    }
    
    public void setGenerarListener(ActionListener listener) {
        btnGenerar.addActionListener(listener);
    }
    public void mostrarDatos(List<VentaDTO> ventas) {
        modelo.setRowCount(0);

        double total = 0;
        double kilos = 0;

        for (VentaDTO v : ventas) {
            modelo.addRow(new Object[]{
                    v.getFecha(),
                    v.getCantidadKG(),
                    v.getMontoTotal()
            });

            total += v.getMontoTotal();
            kilos += v.getCantidadKG();
        }

        lblTotalIngresos.setText("Total: $" + total);
        lblKilosVendidos.setText("Kilos: " + kilos);
    }
    
    public LocalDate getFechaInicio() { 
        try{
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(txtFechaInicio.getText().trim(),formatter);
        }catch(Exception e){
            throw new RuntimeException("Fecha de inicio inválida: " +txtFechaInicio.getText());
        }
    }
    
    public LocalDate getFechaFin() { 
        try{
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(txtFechaFin.getText().trim(),formatter);
        }catch(Exception e){
            throw new RuntimeException("Fecha de fin inválida: " +txtFechaFin.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPresentacionVenta().iniciar();
            }
        });
    }
    
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
